<?php
class Json {
	public $json = '[
	{
		"licenseId":22,"vendorId":31,
		"vendorMediaId":51,
		"name":"Awesome",
		"type":"image",
		"mediaAssets":[
			{
				"id":1,
				"size":"raw",
				"url":"http://localhost/images/img1.png",
				"width":1900,
				"height":1200
			},
			{
				"id":2,
				"size":"tiny",
				"url":"http://localhost/images/img2.png",
				"width":1900,"height":1200
			},
			{
				"id":3,
				"size":"small",
				"url":"http://localhost/images/img3.png",
				"width":1900,
				"height":1200
			}]
	},
	{
		"licenseId":22,
		"vendorId":31,
		"vendorMediaId":51,
		"name":"Coolness",
		"type":"image",
		"mediaAssets":[
		{
			"id":4,
			"size":"raw",
			"url":"http://localhost/images/img4.png",
			"width":1900,
			"height":1200
		},
		{
			"id":5,
			"size":"tiny",
			"url":"http://localhost/images/img5.png",
			"width":1900,
			"height":1200
		},
		{
			"id":6,
			"size":"small",
			"url":"http://localhost/images/img6.png",
			"width":1900,
			"height":1200
		},
		{
			"id":7,
			"size":"medium",
			"url":"http://localhost/images/img7.png",
			"width":1900,
			"height":1200
		},
		{
			"id":8,
			"size":"large",
			"url":"http://localhost/images/img8.png",
			"width":1900,"height":1200
		}]
	},
	{
		"licenseId":22,
		"vendorId":31,
		"vendorMediaId":51,
		"name":"Groovy",
		"type":"image",
		"mediaAssets":[
		{
			"id":9,
			"size":"raw",
			"url":"http://localhost/images/img9.png",
			"width":1900,
			"height":1200
		},
		{
			"id":10,
			"size":"tiny",
			"url":"http://localhost/images/img10.png",
			"width":1900,
			"height":1200
		},
		{
			"id":11,
			"size":"small",
			"url":"http://localhost/images/img11.png",
			"width":1900,
			"height":1200
		}]
	}]';
	
	public function __construct()
	{
		return $this->json;
	}
}
?>